### PR TITLE
fix Observable

### PR DESCRIPTION
**Pull request by AminTakmili**

### CODE REVIEW

**Review by ray-kay — APPROVED** [review]
Looks good, this will help us a lot

**Comment by alexlehner86** [comment]
Yes, please merge this PR quickly. We want to use leaflet-wms-header in a project, but this error is blocking us.

**Comment by alexlehner86** [comment]
Any update on this?

**Comment by HannesWa** [comment]
Would be awesome to have that fix (:

**Comment by ticinum-aerospace** [comment]
same https://github.com/ticinum-aerospace/leaflet-wms-header/pull/7

**Pull request closed without merging**
